# Site settings
title: Cold Fire
description: >
  There is a reason seasons change, they cant hold themselves. Our world is a flowing poetry.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://harshadptl.github.io" # the base hostname & protocol for your site

author:
  fullname: Harshad Patil
 # googleplus: https://www.google.com/+MotaquillahMaddane
  github: harshadptl
  twitter: harrythepatil
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
